document.title= "Hi there!.....JS DOM";
// This will change the title from JavaScript DOM to "Hi there!......JS DOM"....
// document.title is used to select the title of the file and here we have given the value of document.title= "Hi there!.....JS DOM"
// This way the title of webpage have been changed.......
console.log(document.title); // I can print the title of the page through this command...
console.log(document.body); // I can print the whole body of the html through this here.....
// !!! This DOM can only be ran on the console of the browser, it can't run on the terminal through node, it's just and just for browser and web pages.....
document.body.style.backgroundColor = "lightcyan";
// See here, I have written this and this will change the background color of the whole body..
// And whatever css or style I give in here will be added as the inline css for the body, or any element I select through dom will be added as inline property not in the internal or external css or like that
// Just inline css will be added for this
// In our case the body tag will be updated to the <body style = "background-color: lightcyan">
// A window is considered as the main from the browser, like the browser is a part of the windows, like different tabs in windows is referred as the windows, and the browser is also in the window.
// And in window there is document than there is the body and 
// What is BOM Model??