document.title= "Hi there!.....JS DOM";
// This will change the title from JavaScript DOM to "Hi there!......JS DOM"....
// document.title is used to select the title of the file and here we have given the value of document.title= "Hi there!.....JS DOM"
// This way the title of webpage have been changed.......
console.log(document.title); // I can print the title of the page through this command...
console.log(document.body); // I can print the whole body of the html through this here.....
// !!! This DOM can only be ran on the console of the browser, it can't run on the terminal through node, it's just and just for browser and web pages.....