// What are arrays???
// Arrays are a collection of different datatypes in here javascript.....
// Arrays are variables which can store more than one value.
// And the values can also be of different types and data types like bool, var and string in one array...
